// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NexusAstralis.Models.Stars;

public partial class Stars
{
    public double? x { get; set; }

    public double? y { get; set; }

    public double? z { get; set; }

    public string ra { get; set; }

    public string dec { get; set; }

    public string mag { get; set; }

    public string ci { get; set; }

    public string bf { get; set; }

    public string hr { get; set; }

    public string proper { get; set; }

    public double? az { get; set; }

    public double? alt { get; set; }

    public string hip { get; set; }

    public string hd { get; set; }

    public string gl { get; set; }

    public string dist { get; set; }

    public string pmra { get; set; }

    public string pmdec { get; set; }

    public string rv { get; set; }

    public string absmag { get; set; }

    public string spect { get; set; }

    public string vx { get; set; }

    public string vy { get; set; }

    public string vz { get; set; }

    public string rarad { get; set; }

    public string decrad { get; set; }

    public string pmrarad { get; set; }

    public string pmdecrad { get; set; }

    public string bayer { get; set; }

    public string flam { get; set; }

    public string con { get; set; }

    public string comp { get; set; }

    public string comp_primary { get; set; }

    [Column("base")]
    public string _base { get; set; }

    public string lum { get; set; }

    public string var { get; set; }

    public string var_min { get; set; }

    public string var_max { get; set; }

    public string x_gal { get; set; }

    public string y_gal { get; set; }

    public string z_gal { get; set; }

    [Key]
    public int id { get; set; }

    [ForeignKey("star_id")]
    [InverseProperty("star")]
    public virtual ICollection<Constellations> constellation { get; set; } = new List<Constellations>();
}